import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex space-x-5 justify-center">
            <li><Link href='/'>Home</Link></li>
            <li><Link prefetch={false} href='/About'>About</Link></li>
            <li><Link prefetch={false} href='/user'>User</Link></li>
          </ul>
        </nav>
        <div className="h-100">
          {children}
        </div>
        <footer>This Is Footer</footer>
      </body>
    </html>
  );
}
